from django.urls import path

from . import views

urlpatterns = [
    path('panel/', views.VistaPanelControl.as_view(), name='dashboard'),
    path('clientes/', views.VistaListaCliente.as_view(), name='cliente_list'),
    path('clientes/nuevo/', views.VistaCreacionCliente.as_view(), name='cliente_create'),
    path('clientes/<int:pk>/', views.VistaDetalleCliente.as_view(), name='cliente_detail'),
    path('clientes/<int:pk>/editar/', views.VistaEdicionCliente.as_view(), name='cliente_update'),
    path('clientes/<int:pk>/eliminar/', views.VistaEliminacionCliente.as_view(), name='cliente_delete'),
    path('categorias/', views.VistaListaCategoria.as_view(), name='categoria_list'),
    path('categorias/nueva/', views.VistaCreacionCategoria.as_view(), name='categoria_create'),
    path('categorias/<int:pk>/', views.VistaDetalleCategoria.as_view(), name='categoria_detail'),
    path('categorias/<int:pk>/editar/', views.VistaEdicionCategoria.as_view(), name='categoria_update'),
    path('categorias/<int:pk>/eliminar/', views.VistaEliminacionCategoria.as_view(), name='categoria_delete'),
    path('productos/', views.VistaListaProducto.as_view(), name='producto_list'),
    path('productos/nuevo/', views.VistaCreacionProducto.as_view(), name='producto_create'),
    path('productos/<int:pk>/', views.VistaDetalleProducto.as_view(), name='producto_detail'),
    path('productos/<int:pk>/editar/', views.VistaEdicionProducto.as_view(), name='producto_update'),
    path('productos/<int:pk>/eliminar/', views.VistaEliminacionProducto.as_view(), name='producto_delete'),
    path('ventas/', views.VistaListaVenta.as_view(), name='venta_list'),
    path('ventas/nueva/', views.VistaCreacionVenta.as_view(), name='venta_create'),
    path('ventas/<int:pk>/', views.VistaDetalleVenta.as_view(), name='venta_detail'),
    path('ventas/<int:pk>/editar/', views.VistaEdicionVenta.as_view(), name='venta_update'),
    path('ventas/<int:pk>/eliminar/', views.VistaEliminacionVenta.as_view(), name='venta_delete'),
    path('garantias/', views.VistaListaGarantia.as_view(), name='garantia_list'),
    path('garantias/nueva/', views.VistaCreacionGarantia.as_view(), name='garantia_create'),
    path('garantias/<int:pk>/', views.VistaDetalleGarantia.as_view(), name='garantia_detail'),
    path('garantias/<int:pk>/editar/', views.VistaEdicionGarantia.as_view(), name='garantia_update'),
    path('garantias/<int:pk>/eliminar/', views.VistaEliminacionGarantia.as_view(), name='garantia_delete'),
    path('casos/', views.VistaListaCaso.as_view(), name='caso_list'),
    path('casos/nuevo/', views.VistaCreacionCaso.as_view(), name='caso_create'),
    path('casos/<int:pk>/', views.VistaDetalleCaso.as_view(), name='caso_detail'),
    path('casos/<int:pk>/editar/', views.VistaEdicionCaso.as_view(), name='caso_update'),
    path('casos/<int:pk>/eliminar/', views.VistaEliminacionCaso.as_view(), name='caso_delete'),
    path('casos/<int:caso_id>/avanzar/', views.avanzar_estado_caso, name='caso_avanzar'),
    path('diagnosticos/', views.VistaListaDiagnostico.as_view(), name='diagnostico_list'),
    path('diagnosticos/nuevo/', views.VistaCreacionDiagnostico.as_view(), name='diagnostico_create'),
    path('diagnosticos/<int:pk>/', views.VistaDetalleDiagnostico.as_view(), name='diagnostico_detail'),
    path('diagnosticos/<int:pk>/editar/', views.VistaEdicionDiagnostico.as_view(), name='diagnostico_update'),
    path('diagnosticos/<int:pk>/eliminar/', views.VistaEliminacionDiagnostico.as_view(), name='diagnostico_delete'),
    path('evidencias/', views.VistaListaEvidencia.as_view(), name='evidencia_list'),
    path('evidencias/nueva/', views.VistaCreacionEvidencia.as_view(), name='evidencia_create'),
    path('evidencias/<int:pk>/', views.VistaDetalleEvidencia.as_view(), name='evidencia_detail'),
    path('evidencias/<int:pk>/editar/', views.VistaEdicionEvidencia.as_view(), name='evidencia_update'),
    path('evidencias/<int:pk>/eliminar/', views.VistaEliminacionEvidencia.as_view(), name='evidencia_delete'),
    path('estados/', views.VistaListaEstado.as_view(), name='estado_list'),
    path('estados/nuevo/', views.VistaCreacionEstado.as_view(), name='estado_create'),
    path('estados/<int:pk>/', views.VistaDetalleEstado.as_view(), name='estado_detail'),
    path('estados/<int:pk>/editar/', views.VistaEdicionEstado.as_view(), name='estado_update'),
    path('estados/<int:pk>/eliminar/', views.VistaEliminacionEstado.as_view(), name='estado_delete'),
    path('historial/', views.VistaListaHistorial.as_view(), name='historial_list'),
    path('historial/nuevo/', views.VistaCreacionHistorial.as_view(), name='historial_create'),
    path('historial/<int:pk>/', views.VistaDetalleHistorial.as_view(), name='historial_detail'),
    path('historial/<int:pk>/editar/', views.VistaEdicionHistorial.as_view(), name='historial_update'),
    path('historial/<int:pk>/eliminar/', views.VistaEliminacionHistorial.as_view(), name='historial_delete'),
    path('entregas/', views.VistaListaEntrega.as_view(), name='entrega_list'),
    path('entregas/nueva/', views.VistaCreacionEntrega.as_view(), name='entrega_create'),
    path('entregas/<int:pk>/', views.VistaDetalleEntrega.as_view(), name='entrega_detail'),
    path('entregas/<int:pk>/editar/', views.VistaEdicionEntrega.as_view(), name='entrega_update'),
    path('entregas/<int:pk>/eliminar/', views.VistaEliminacionEntrega.as_view(), name='entrega_delete'),
]

