# Generated by Django 4.2.26 on 2026-05-20 22:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descripcion_falla', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=10)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'caso de reparacion',
                'verbose_name_plural': 'casos de reparacion',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria de producto',
                'verbose_name_plural': 'categorias de productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingresa un telefono valido.', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=180)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#2563eb', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('es_final', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'estado de caso',
                'verbose_name_plural': 'estados de casos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('serial', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='garantias.categoriaproducto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['marca', 'modelo', 'serial'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_factura', models.CharField(max_length=60, unique=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='garantias.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='garantias.producto')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(blank=True, max_length=240)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='garantias.casoreparacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='garantias.estadocaso')),
            ],
            options={
                'verbose_name': 'historial de estado',
                'verbose_name_plural': 'historial de estados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='vigente', max_length=12)),
                ('condiciones', models.TextField(blank=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='garantia', to='garantias.venta')),
            ],
            options={
                'verbose_name': 'garantia',
                'verbose_name_plural': 'garantias',
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('diagnostico', 'Diagnostico'), ('reparacion', 'Reparacion'), ('entrega', 'Entrega')], default='ingreso', max_length=15)),
                ('imagen', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('descripcion', models.CharField(max_length=220)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='garantias.casoreparacion')),
            ],
            options={
                'verbose_name': 'evidencia',
                'verbose_name_plural': 'evidencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('entregado_a', models.CharField(max_length=120)),
                ('documento_entrega', models.CharField(max_length=30)),
                ('recibido_conforme', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='garantias.casoreparacion')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tecnico', models.CharField(max_length=120)),
                ('diagnostico', models.TextField()),
                ('solucion', models.TextField(blank=True)),
                ('requiere_repuesto', models.BooleanField(default=False)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='garantias.casoreparacion')),
            ],
            options={
                'verbose_name': 'diagnostico',
                'verbose_name_plural': 'diagnosticos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='casoreparacion',
            name='estado_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_actuales', to='garantias.estadocaso'),
        ),
        migrations.AddField(
            model_name='casoreparacion',
            name='garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='garantias.garantia'),
        ),
    ]
